package hpl.comp;

import java.lang.Integer;
import java.lang.String;
import java.lang.System;
import java.util.ArrayList;

public class Initialiser implements CompilerResult
{
	private CompilerResult paintResult;

	private StringBuilder builder = new StringBuilder("<?xml version=\"1.0\" standalone=\"no\"?> \n" +
			"<!DOCTYPE svg PUBLIC \"-//W3C//DTD SVG 1.1//EN\" \n" +
			"\"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd\"> \n" +
			"<svg width=\"7cm\" height=\"8cm\" viewBox=\"0 0 700 800\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\"> \n" +
			"<desc>Translated from HPL </desc> \n" +
			"<!-- ECMAScript generated by translator -->\n" +
			"<g id=\"screen\" x=\"0\" y=\"0\" width=\"100%\" height=\"100%\" transform=\"translate(50, 50) scale(600, 600)\" >\n" +
			"<rect x=\"0\" y=\"0\" width=\"1.0\" height=\"1.0\" stroke=\"blue\" stroke-width=\"0.01\"/>\n" +
			"</g>\n" +
			"\n" +
			"  <!-- Act on each click event -->\n" +
			"<text x=\"300\" y=\"680\" font-family=\"Verdana\" font-size=\"30\" text-anchor=\"middle\" >\n" +
			"Click in the box if it is blank\n" +
			"</text> \n" +
			"</svg>\n");

	public void setPaintResult(CompilerResult stmt)
	{
		if(stmt != null) {
			this.paintResult = stmt;
			builder.insert(builder.lastIndexOf("</g>"), paintResult.gen());
		}
	}

    public String gen()
    {
    	return builder.toString();
    }
}